import fs from "node:fs";import path from "node:path";import { DatabaseSync } from "node:sqlite";import { fileURLToPath } from "node:url";
import { emitEvent } from "./plugin-bus.mjs";import { indexSemanticMessage } from "./semantic-store.mjs";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");const dataDir=process.env.GMAIL_CONTROL_DATA_DIR?path.resolve(process.env.GMAIL_CONTROL_DATA_DIR):path.join(root,"data");fs.mkdirSync(dataDir,{recursive:true});
let database;function db(){if(database)return database;const p=path.join(dataDir,"ingestion.sqlite3");database=new DatabaseSync(p);database.exec("PRAGMA journal_mode=WAL;CREATE TABLE IF NOT EXISTS cursors(account_id TEXT PRIMARY KEY,history_id TEXT NOT NULL,updated_at TEXT NOT NULL);");try{fs.chmodSync(p,0o600)}catch{}return database}
export function parsePubSubEnvelope(body){const encoded=body?.message?.data;if(!encoded)throw new Error("Pub/Sub message.data is required.");let data;try{data=JSON.parse(Buffer.from(encoded,"base64").toString("utf8"))}catch{throw new Error("Invalid Pub/Sub Gmail notification payload.")}if(!data.emailAddress||!data.historyId)throw new Error("Gmail notification requires emailAddress and historyId.");return {emailAddress:String(data.emailAddress).toLowerCase(),historyId:String(data.historyId),messageId:String(body?.message?.messageId||"")}}
export function getHistoryCursor(accountId){return db().prepare("SELECT history_id FROM cursors WHERE account_id=?").get(String(accountId))?.history_id||""}
export function setHistoryCursor(accountId,historyId){db().prepare(`INSERT INTO cursors(account_id,history_id,updated_at) VALUES(?,?,?) ON CONFLICT(account_id) DO UPDATE SET history_id=excluded.history_id,updated_at=excluded.updated_at`).run(String(accountId),String(historyId),new Date().toISOString());return String(historyId)}
export async function processNotification(body,{resolveAccount,historySince,readMessage,embeddingOptions={}}){const note=parsePubSubEnvelope(body);const account=await resolveAccount(note.emailAddress);if(!account)throw new Error("No configured account for "+note.emailAddress);const previous=getHistoryCursor(account.id);if(!previous){setHistoryCursor(account.id,note.historyId);await emitEvent("gmail.cursor.initialized",{account,notification:note});return {accountId:account.id,historyId:note.historyId,indexed:[],initialized:true}}
 const changes=await historySince(account.id,previous);const indexed=[],seen=new Set();for(const change of changes.messagesAdded||[]){const id=change.message?.id||change.id;if(!id||seen.has(id))continue;seen.add(id);const message=await readMessage(account.id,id);await indexSemanticMessage(account.id,message,embeddingOptions);indexed.push(id);await emitEvent("message.received",{account,message})}
 const next=changes.historyId||note.historyId;setHistoryCursor(account.id,next);await emitEvent("gmail.history",{account,notification:note,indexed,previousHistoryId:previous,nextHistoryId:next});return {accountId:account.id,historyId:next,indexed,initialized:false}}
